### PR TITLE
add safeParse to benchmarks

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
@mcollina 

Somehow legacy tests fail. I assume because we did not pin tsd

**Review by Uzlopak — COMMENTED** [review]
Dont merge yet

**Comment by Uzlopak** [comment]
I merge it as the ci cd pipeline works now properly and I got an approval ;)

**Pull request merged**
