### PR TITLE
fix: support parsing buffers

### PR DESCRIPTION
**Pull request by jkirkpatrick24**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added (no changes needed)*
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

# Summary

When `parse` is called with a Buffer, an error was being thrown because we were attempting to call text.charCodeAt which doesn't exist for buffers. This simply adds a check if charCodeAt exists before attempting to invoke it.

### CODE REVIEW

**Comment by mcollina** [comment]
charCodeAt is needed in that place. We should convert to string before parsing.

**Comment by kibertoad** [comment]
@mcollina I'm concerned that no tests are failing despite that operation being needed. Can you elaborate why it's essential, and what kind of test might allow us to test for that scenario?

**Review by kibertoad — APPROVED** [review]

**Comment by jkirkpatrick24** [comment]
Thanks for reviewing! Updated and added an extra test.

**Review by L2jLiga — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
