### PR TITLE
Update for Fastify v5

### PR DESCRIPTION
**Pull request by gurgunday**

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
There is no need to drop old nodes for this

**Comment by gurgunday** [comment]
We just add pre-commit here

We can close the PR or just merge to `master`

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
why target next? This can land in main

**Comment by gurgunday** [comment]
I might try to migrate to `tap` before merging

**Review by Fdawgs — APPROVED** [review]

**Pull request merged**
