### PR TITLE
Add benchmark results to readme

### PR DESCRIPTION
**Pull request by anthonyringoet**
As title states, added benchmark results to readme.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please change `Bourne.parse` to `secure-json-parse`? thanks

**Comment by anthonyringoet** [comment]
Yes, that makes sense. Updated the readme and benchmark files.

**Comment by anthonyringoet** [comment]
@RafaelGSS Personal notebook. It is certainly not free of possible external impacts as it's not a standardized testing setup. It's always running _some_ other software.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
