### PR TITLE
Dropped .npmignore

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #24 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by L2jLiga — APPROVED** [review]
lgtm

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by kibertoad** [comment]
@mcollina Shouldn't `files` be added to package.json then? Now we are going to be publishing plenty of additional noise files, which can be undesired, especially for browser usage.

**Comment by mcollina** [comment]
they won't be included in the bundle anyway - we are talking about 4KB that will be downloaded and placed on disk during development.

Managing .npmignore and/or files is just awkward, I just prefer to have all contents pushed.

**Pull request merged**
