### PR TITLE
feat: add an overload function to `parse`

### PR DESCRIPTION
**Pull request by timursaurus**
Added an overload function type to `parse` which provides a better developer experience and makes typescript happy
By adding an overload, we don't have to use `@ts-expect-error` flag, when only 2 arguments are passed to `parse` like in this [example](https://github.com/elastic/elastic-transport-js/blob/main/src/Serializer.ts#L61)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — CHANGES_REQUESTED** [review]
Would you mind to add a test?

**Comment by timursaurus** [comment]
> Would you mind to add a test?
Sure, as soon as I get a chance
I think rewriting some of the test would also beneficial, as there's no need to pass `null` to `reviver` in type tests

**Review by Eomm — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Eomm** [comment]
I can't release it due to permission

**Pull request merged**
