### PR TITLE
perf: Improve performance of safeParse in case of malicious payload

### PR DESCRIPTION
**Pull request by Uzlopak**
This PR improves the performance in case malicious payload is provided.

Breaking Change:
- Removed the scan-function

before:

```
node valid
JSON.parse x 1,684,201 ops/sec ±0.74% (90 runs sampled)
JSON.parse proto x 1,090,668 ops/sec ±1.10% (87 runs sampled)
secure-json-parse parse x 1,437,734 ops/sec ±0.97% (88 runs sampled)
secure-json-parse parse proto x 1,580,499 ops/sec ±0.96% (87 runs sampled)
secure-json-parse safeParse x 1,420,574 ops/sec ±0.88% (87 runs sampled)
secure-json-parse safeParse proto x 136,433 ops/sec ±0.78% (90 runs sampled)
JSON.parse reviver x 500,856 ops/sec ±0.58% (89 runs sampled)
Fastest is JSON.parse
```

after:
```
JSON.parse x 1,725,767 ops/sec ±0.75% (91 runs sampled)
JSON.parse proto x 1,089,860 ops/sec ±0.71% (90 runs sampled)
secure-json-parse parse x 1,454,987 ops/sec ±0.73% (93 runs sampled)
secure-json-parse parse proto x 1,570,482 ops/sec ±0.66% (89 runs sampled)
secure-json-parse safeParse x 1,491,839 ops/sec ±0.91% (92 runs sampled)
secure-json-parse safeParse proto x 993,249 ops/sec ±0.95% (87 runs sampled)
JSON.parse reviver x 501,228 ops/sec ±0.79% (92 runs sampled)
Fastest is JSON.parse
```

### CODE REVIEW

**Comment by mcollina** [comment]
Given the implementation of `safeParse()` (which is just a try/catch()), I don't understand why
we had such a big discrepancy in the benchmark to begin with: 1,580,499 vs 136,433. From the look of if you have altered the benchmarks and the tests `secure-json-parse parse` and `secure-json-parse safeParse` are called with different settings. I think it would be better to not check `safeParse` in benchmarks but just focus on the settings of `secure-json-parse parse`.

Note that fastify does not use `safeParse` at all (ref: https://github.com/fastify/fastify/blob/a985b698628fdeeced6d416c4e4f964e2cdb46dd/lib/contentTypeParser.js#L260). Will it be impacted by this change?

**Comment by Uzlopak** [comment]
@mcollina 

Well instead of throwing it returns null, so no stack trace overhead. 

But if you want i can just create a PR where no active code change exists, but modification on types etc..

**Comment by mcollina** [comment]
the whole point of `safeParse` vs `parse` is to throw.

Note that the gap between

secure-json-parse safeParse proto x 136,433 ops/sec ±0.78% (90 runs sampled)

and

secure-json-parse safeParse proto x 993,249 ops/sec ±0.95% (87 runs sampled)

cannot be attributed to a try-catch.

**Comment by Uzlopak** [comment]
Just to be on the same page:
safeParse is about not to throw but to return null

**Comment by mcollina** [comment]
I'm sorry but I don't understand this sentence:

> Well instead of throwing it returns null, so no stack trace overhead.

You are right that `safeParse()` was always returning `null`. So where is the breaking change?

**Comment by Uzlopak** [comment]
safeParse runs in the original implementation in a try catch block. 

Now when in safeParse the object is validated to not contain malicious keys, it does not throw a SyntaxError just to be caught in the try catch, but returns null. So no strack trace to be genearated, which gets neglected anyway.

**Comment by mcollina** [comment]
Why did you remove `scan` then?

**Comment by Uzlopak** [comment]
Because I assume it was only exported for unit tests.Also i wanted to avoid unecessary branches

**Comment by mcollina** [comment]
Consider that Fastify uses `.parse()`: https://github.com/fastify/fastify/blob/main/lib/contentTypeParser.js#L267-L272.

**Comment by Uzlopak** [comment]
I will investigate further.Closing this for now. ;)

**Pull request closed without merging**
