### PR TITLE
add types

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Adds typescript types for the `secure-json-parse` functions.

The `any` return types are not ideal (it could be better to return `unknown` and force an explicit cast) but this way it's the same as `JSON.parse()`.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Could you add a test test for the types using `tsd`?

**Comment by goto-bus-stop** [comment]
yep--turns out i made a mistake in the declarations the first time round! should be accurate now.

**Comment by goto-bus-stop** [comment]
looks like tsd doesn't support <10.x (even the versions that claim to support 8.x pull in dependencies that no longer do).
Don't know if there's precedent in the fastify org for this, I could add an `npm run test-legacy` for that doesn't run tsd so node 6 and 8 can still be tested on CI. does that sound good?

**Comment by mcollina** [comment]
good for me!

**Review by L2jLiga — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
